defaults:
  - dataset/key_formatter: remove_prefix

offline_steps: 140000
batch_size: 8
num_workers: 4
device: cuda

dataset:
  _target_: lecoro.common.datasets.lecoro_dataset.LeCoroDataset
  root: ${root}/datasets/${dataset_repo_id}
  repo_id: ${dataset_repo_id}
  episodes: null  # all
  download_videos: true
  local_files_only: false
  video_backend: ${video_backend}
