defaults:
  - dataset/key_formatter: remove_prefix

batch_size: 4
num_workers: 0
device: cpu

dataset:
  _target_: coro.common.dataset.lecoro_dataset.LeCoroDataset
  root: ${root}/datasets/${dataset_repo_id}
  repo_id: ${dataset_repo_id}
  episodes: null  # all
  download_videos: true
  local_files_only: false
  video_backend: ${video_backend}
