# @package _global_
defaults:
  - override /observation/encoder/rgb/backbone: resnet18_pretrained

observation:
  encoder:
    rgb:
      backbone:
        replace_final_stride_with_dilation: false
        norm_cfg:
          name: frozen_batch_norm

      share_backbone: true

      normalization_stats:
        # stats from imagenet, since we use a pretrained resnet
        mean: [ [ [ 0.485 ] ], [ [ 0.456 ] ], [ [ 0.406 ] ] ]  # (c,1,1)
        std: [ [ [ 0.229 ] ], [ [ 0.224 ] ], [ [ 0.225 ] ] ]  # (c,1,1)
