# @package _global_
defaults:
  - override /observation/encoder/rgb/randomizer/1: crop_randomizer
  - override /observation/encoder/rgb/backbone: resnet18_pretrained
  - override /observation/encoder/rgb/projection: flatten
  - override /observation/encoder/rgb/activation: identity

  - override /observation/encoder/rgb/randomizer/1: crop_randomizer
  - override /observation/encoder/rgb/backbone: resnet18
  - override /observation/encoder/rgb/projection: flatten
  - override /observation/encoder/rgb/activation: identity

observation:
  encoder:
    rgb:
      normalization_stats:
        # stats from imagenet, since we use a pretrained vision model
        mean: [ [ [ 0.485 ] ], [ [ 0.456 ] ], [ [ 0.406 ] ] ]  # (c,1,1)
        std: [ [ [ 0.229 ] ], [ [ 0.224 ] ], [ [ 0.225 ] ] ]  # (c,1,1)


